name: Publish Historical Tags

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma-separated tags to publish'
        required: true

jobs:
  publish:
    uses: GameFrameX/public-github-actions/.github/workflows/publish-historical-tags.yml@main
    with:
      tags: ${{ github.event.inputs.tags }}
    secrets: inherit
